### ISSUE TITLE
Only return web scene on the Gallery page 

### ISSUE THREAD

**Issue by TinaJin** [VBZelin/appstudio_3d_viewer#1]
## Issue Description:
Currently, when the user enters an item ID/ search keyword (not Web Scene), you are still able to see it/them on the Gallery page. In this case, we should only return Web Scenes on the Gallery page. 

## To Reproduce:
1. Download latest code from this repo
2. Bring it to AppStudio Desktop 
3. Go to **Settings** > **Gallery** > **Map query** 
4. Enter the following item ID/ keyword into **Map query** field 

 - 02723800a14947e68313caefeb2eeff5 (type: CityEngine Web Scene)
 - f2ececd0e30445e8ab45c6f138a864ad(type: Web Map)
 - Redlands
5. Run the app and go to Gallery Page

**Comment by VBZelin** [comment]
@TinaJin This issue has been fixed in #2. Please verify.

**Comment by TinaJin** [comment]
Verified. Looks good. Closing this issue
