### ISSUE TITLE
Do not show web scenes when version is not greater than 1.10.0 and viewing Mode is not global

### ISSUE THREAD

**Issue by TinaJin** [VBZelin/appstudio_3d_viewer#11]
## Issue Description: 
Based on the [ArcGIS Runtime web scene API guide](https://developers.arcgis.com/qt/latest/qml/guide/runtime-support-for-the-web-scene-specification.htm), the ArcGIS Runtime supports only scenes with the following values set:

- version - 1.10.0 or greater
- viewingMode - global 

Currently, the 3D Viewer sample app is able to show the thumbnail of these web scenes, however, it won't open them, see screenshot below. 

![image](https://user-images.githubusercontent.com/19921422/56702559-936eb600-66b9-11e9-9ea1-caf6b2c8948c.png)

In this case, it would be nice to filter out these web scenes. If it is hard to do so, please show a pop-up with the warning message as an alternative option. 

## Notes:
Web Scene for testing:

- 273d1c2d061f43bc99b5f86c41b6001b (Local Web Scene)

**Comment by VBZelin** [comment]
Implementation:
- Added error message popups to the info page, we are using loadError instead of error property. The reason is that loading scene map may trigger too many errors, and we only need loadError for now.

**Comment by VBZelin** [comment]
@Tina Ready for verification.

**Comment by TinaJin** [comment]
@VBZelin 
Verified, looks good. Nice I see a pop-up with error messages.
