### ISSUE TITLE
Show load error message in a pop up when the user was not able to open a web scene

### ISSUE THREAD

**Issue by TinaJin** [VBZelin/appstudio_3d_viewer#12]
## Issues Description:
Show [load error message](https://developers.arcgis.com/qt/latest/qml/api-reference/qml-esri-arcgisruntime-error.html) in a pop up when the user was not able to open a web scene. This will be very helpful in a case like when the user provides a secured web scene, it would be nice to show a warning message to inform the user that "Currently, only public web scenes are supported". 

## Notes:
Web Scene for testing:

- Secured Web Scene: https://www.arcgis.com/home/item.html?id=1142c948142f40b5947c603759a482cd

**Comment by VBZelin** [comment]
This issue has been fixed in #11.

**Comment by VBZelin** [comment]
@TinaJin Ready for verification.

**Comment by TinaJin** [comment]
@VBZelin 
Verified, looks good. Nice I see a pop-up with error messages.
