### ISSUE TITLE
Support for changing primary color 

### ISSUE THREAD

**Issue by TinaJin** [VBZelin/appstudio_3d_viewer#14]
## Requirement

We are planning to release this 3D Viewer sample as a template and it is required to allow users to change primary/branding color for the app just like other templates.  

Assigning this issue to Qun to provide a design.

**Comment by VBZelin** [comment]
REF: #14 

Implementations:
- Added primary color to the app, users can change it through app settings
- Updated the visual effect in the app
- Fixed a null thumbnail issue

Screenshots:
![Screen Shot 2019-05-09 at 5 51 16 PM](https://user-images.githubusercontent.com/14915451/57495535-79210480-7283-11e9-852b-4d233785f34e.png)
![Screen Shot 2019-05-09 at 5 51 31 PM](https://user-images.githubusercontent.com/14915451/57495536-79210480-7283-11e9-98b5-cf1feebb2959.png)
![Screen Shot 2019-05-09 at 5 52 40 PM](https://user-images.githubusercontent.com/14915451/57495537-79210480-7283-11e9-99e6-75e374142eba.png)

**Comment by VBZelin** [comment]
@TinaJin Ready for verification.

**Comment by TinaJin** [comment]
@VBZelin 

Verified, it looks good. I made some small changes to the app and created a PR.  Could you please merge it.
The PR includes changes for:

- Changed the default branding color to AppStudio's branding color
- Increased location display size to 13 and white outline size to 2
- Changed location icon color to steel blue to make it consistent with Map Viewer template
- Changed location display circle color to steel blue to make it consistent with Map Viewer template

**Comment by TinaJin** [comment]
@VBZelin 
Verified, it looks good. Closing this issue
