### ISSUE TITLE
Default Web Scenes should return when Maps query field is empty

### ISSUE THREAD

**Issue by TinaJin** [VBZelin/appstudio_3d_viewer#2]
## Issue Description:
Currently, when the user entered something in the Maps query field, then remove it, in this case, default Web Scenes should return to the **Gallery** page instead of empty. 

## To Reproduce:
1. Select 3D Viewer app on AppStudio Desktop
2. Go to **Settings > Gallery > Maps query**
3. Enter an item ID or search keyword, such as"Redlands" > **Apply**
4. Remove "Redlands" and **Apply** again
5. Run the app and you will find Gallery page is empty 

## Other issues 

- [x] Could you also hide **Settings** icon on the **Gallery** page 
- [x] Change **Maps query** in the _appschema.json_ file into **Web Scene query**
- [x] Change the sorting field based on latest date

![image](https://user-images.githubusercontent.com/19921422/55912300-45c15c00-5b97-11e9-8e42-b0db0ac28145.png)

**Comment by VBZelin** [comment]
Implementations:
- Set default value to type: web scene if the search query is empty
- Hid Settings icon on the Gallery page
- Changed Maps query in the appschema.json file into Web Scene query
- Change the sorting field based on latest date

**Comment by VBZelin** [comment]
@TinaJin Ready for verification.

**Comment by nmanocha** [comment]
Verified
- [ ] Settings is hidden
- [ ] Sorted based on last modified works
- [ ] Change Maps query in the appschema.json file into Web Scene query
