### ISSUE TITLE
Remove dot dot dot icon on the right of the header on Windows platform 

### ISSUE THREAD

**Issue by TinaJin** [VBZelin/appstudio_3d_viewer#5]
## Issues Desktop:

Two users from holistic testing both reported that dot dot dot icon is not working on Windows platform.  

## Solution:
Since share sheet is not supported on the Windows, we should remove dot dot dot icon for Windows platform.

**Comment by VBZelin** [comment]
Implementation:
- Hide share sheet button for windows

**Comment by VBZelin** [comment]
@TinaJin Ready for verification.

**Comment by TinaJin** [comment]
![image](https://user-images.githubusercontent.com/19921422/56391760-6f583400-61e4-11e9-9c22-0757463ee37b.png)

Verified on Windows, it looks good. Closing this issue.
