### ISSUE TITLE
Location enhancements 

### ISSUE THREAD

**Issue by TinaJin** [VBZelin/appstudio_3d_viewer#7]
- [x] 1. Show a graphic such as blue dot to indicate device location
- [x] 2. Increase Z value 
- [x] 3. Disable location source when clicking on the **Home** icon 
- [x] 4. Do not show Location Access Disabled popup on Windows, MacOS, and Linux

**Comment by VBZelin** [comment]
Implementation:
- Displayed a graphic such as blue dot to indicate device location
- Increased Z value
- Disabled location source when clicking on the Home icon
- Hide Location Access Disabled popup on Windows, MacOS, and Linux
